= yuqo2450.k3s.install
:hardbreaks-option:

This role is meant to install a k3s cluster on any number of nodes consisting of both controllers and agents. Despite it can be used to install a single node k3s cluster.

== Requirements

This role requires your inventory to be setup correctly. This is required because it will install both kubernetes controllers and agents.
To distinguish, it is required to add a `kubec-controller` and `kubec-agent` group in your inventory:
----
---
all:
  hosts:
    kube-ctrl01:
      ansible-host: 192.168.1.11
    kube-ctrl02:
      ansible-host: 192.168.1.12
    kube-ctrl03:
      ansible-host: 192.168.1.13
    kube-agent01:
      ansible_host: 192.168.1.21
    kube-agent02:
      ansible_host: 192.168.1.22
    kube-agent03:
      ansible_host: 192.168.1.23
  children:
    kube-controller:
      hosts:
        kube-ctrl01
        kube-ctrl02
        kube-ctrl03
    kube-agent:
      hosts:
        kube-agent01
        kube-agent02
        kube-agent03

----

== Role Variables

A description of the settable variables for this role should go here, including any variables that are in defaults/main.yml, vars/main.yml, and any variables that can/should be set via parameters to the role. Any variables that are read from other roles and/or the global scope (ie. hostvars, group vars, etc.) should be mentioned here as well.

== Dependencies

A list of other roles hosted on Galaxy should go here, plus any details in regards to parameters that may need to be set for other roles, or variables that are used from other roles.

== Example Playbook

Including an example of how to use your role (for instance, with variables passed in as parameters) is always nice for users too:

    - hosts: servers
      roles:
         - { role: username.rolename, x: 42 }

== License

GPL-3.0-only

== Author Information

This role was created by Daniel Rossa.
