---
# defaults file for install
version: v1.28.1
controller_group: kube-controller
agent_group: kube-agent
bin_path: /usr/local/bin
https_port: 6443
# Allowed values: vxlan, host-gw, wireguard-native
flannel_backend: vxlan
# Allowed values: cloud-controller, helm-controller, network-policy, scheduler, kube-proxy
disable_components: []
# Allowed values: coredns, traefik, local-storage, metrics-server, servicelb
disable_addons: []
