---
# defaults file for install
install_version: v1.28.2
install_controller_group: kube-controller
install_agent_group: kube-agent
install_bin_path: /usr/local/bin
install_https_port: 6443
# Allowed values: vxlan, host-gw, wireguard-native
install_flannel_backend: vxlan
# Allowed values: cloud-controller, helm-controller, network-policy, scheduler, kube-proxy
install_disable_components: []
# Allowed values: coredns, traefik, local-storage, metrics-server, servicelb
install_disable_addons: []
