---
# tasks file for uninstall
# code: language=ansible
- name: Ensure k3s service is stopped
  ansible.builtin.service:
    name: k3s.service
    state: stopped
    enabled: false
  register: k3s_service_present
  failed_when:
    - k3s_service_present.failed
    - "'Could not find the requested service' not in k3s_service_present.msg"

- name: Reload systemd
  ansible.builtin.systemd:
    daemon_reload: true

- name: Undo prerequisites
  block:
    - name: Allow ipv4 forwarding
      ansible.posix.sysctl:
        name: net.ipv4.ip_forward
        value: 1
        state: absent

    - name: Allow ipv6 forwarding
      ansible.posix.sysctl:
        name: net.ipv6.conf.all.forwarding
        value: 1
        state: absent

    - name: Accept ipv6 router advertisment
      ansible.posix.sysctl:
        name: net.ipv6.conf.all.accept_ra
        value: 2
        state: absent

    - name: Load kernel module br_netfilter
      community.general.modprobe:
        name: br_netfilter
        state: absent

- name: Remove files and directories
  block:
    - name: Remove config dirs
      ansible.builtin.file:
        path: "{{ item }}"
        state: absent
      loop: "{{ uninstall_config_dirs }}"

    - name: Remove k3s biaries and scripts
      ansible.builtin.file:
        path: "{{ uninstall_bin_path }}/{{ item }}"
        state: absent
      loop: ["k3s", "k3s-killall.sh", "k3s-{{ uninstall_version }}"]

    - name: Remove k3s service
      ansible.builtin.file:
        path: /usr/lib/systemd/system/k3s.service
        state: absent
  rescue:
    - name: Rerun killall script
      ansible.builtin.command:
        cmd: "{{ uninstall_bin_path }}/k3s-killall.sh"
      changed_when: false
