---
# code: language=ansible
argument_spec:
  main:
  options:
    install_version:
      description: kubernetes version to be installed
      type: str
      required: false
      default: v1.28.1
    install_controller_group:
      description: Name of the inventory group used for controll nodes
      type: str
      required: false
      default: kube-controller
    install_argent_group:
      description: Name of the inventory group used for agent nodes
      type: str
      required: false
      default: kube-agent
    install_bin_path:
      description: Local path where k3s binary will be installed to.
      type: str
      required: false
      default: /usr/local/bin
    install_https_port:
      description: Port used on the nodes for api connection
      type: int
      required: false
      default: 6443
    install_flannel_backend:
      description: Backend used for flannel
      type: list
      elements: str
      choices: [vxlan, host-gw, wireguard-native]
      required: false
      default: vxlan
    install_disable_components:
      description: Kubernetes componentes to be disabled on the node
      type: list
      elements: str
      choices: [cloud-controller, helm-controller, network-policy, scheduler, kube-proxy]
      required: false
      default: []
    install_disable_addons:
      description: Additional workloads to be deployed on install
      type: list
      elements: str
      choices: [coredns, traefik, local-storage, metrics-server, servicelb]
      required: false
      default: []
    install_api_ip:
      description: Loadbalancer IP to be used to connect to api
      type: str
      required: false
    install_lb_iface:
      description: Name of the interfaced used for kube-vip
      type: str
      required: false
    install_svclb_ips:
      description: IP ranges to be used for kubernetes LoadBalancer services
      type: dict
      required: false
    install_taints:
      description: Taints to be applied to kubernetes nodes
      type: list
      elements: str
      default: []
