---
# vars file for install
k3s_config_dirs:
  - /var/lib/rancher/k3s/server/manifests
  - /etc/rancher/k3s/config.yaml.d
controller_ips: "{{ groups[controller_group] | map('extract', hostvars) | map(attribute='ansible_host') }}"
