---
# vars file for install
k3s_config_dirs: 
  - /var/lib/rancher/k3s/server/manifests
  - /var/lib/rancher/k3s/server
  - /var/lib/rancher/k3s
  - /var/lib/rancher
  - /etc/rancher/k3s/config.yaml.d
  - /etc/rancher/k3s
  - /etc/rancher
controller_ips: "{{ groups[controller_group] | map('extract', hostvars) | map(attribute='ansible_host') }}"
